language: go
sudo: false
go:
  - 1.8
  - tip

before_install:
  - go get -u -t ./...

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

comment: off
